services:
  db:
    image: mysql:8.3
    container_name: parcauto-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      # Correction : chemin relatif sans espace, recommandé pour Windows
      - "./db:/docker-entrypoint-initdb.d"
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - parcauto-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: parcauto-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - parcauto-network

volumes:
  mysql_data:

networks:
  parcauto-network:
    driver: bridge